packages:
  - name: k3s-openrc
    category: k8s
    version: "1.25.11+2"
    k3s_version: "2"
    labels:
      github.owner: "k3s-io"
      github.repo: "k3s"
    uri:
      - https://github.com/k3s-io/k3s
    license: "APL-2"
    description: " Lightweight Kubernetes "
  - name: k3s-openrc
    category: k8s
    version: "1.26.6+2"
    k3s_version: "2"
    labels:
      github.owner: "k3s-io"
      github.repo: "k3s"
    uri:
      - https://github.com/k3s-io/k3s
    license: "APL-2"
    description: " Lightweight Kubernetes "
  - name: k3s-openrc
    category: k8s
    version: "1.27.3+2"
    k3s_version: "2"
    labels:
      github.owner: "k3s-io"
      github.repo: "k3s"
    uri:
      - https://github.com/k3s-io/k3s
    license: "APL-2"
    description: " Lightweight Kubernetes "
  - name: k3s-systemd
    category: k8s
    version: "1.28.3-rc1+k3s1"
    k3s_version: "2"
    labels:
      github.owner: "k3s-io"
      github.repo: "k3s"
    uri:
      - https://github.com/k3s-io/k3s
    license: "APL-2"
    description: " Lightweight Kubernetes "
  - name: k3s-systemd
    category: k8s
    version: "1.26.6+2"
    k3s_version: "2"
    labels:
      github.owner: "k3s-io"
      github.repo: "k3s"
    uri:
      - https://github.com/k3s-io/k3s
    license: "APL-2"
    description: " Lightweight Kubernetes "
  - name: k3s-systemd
    category: k8s
    version: "1.27.3+2"
    k3s_version: "2"
    labels:
      github.owner: "k3s-io"
      github.repo: "k3s"
    uri:
      - https://github.com/k3s-io/k3s
    license: "APL-2"
    description: " Lightweight Kubernetes "
