packages:
  - name: k3s-openrc
    category: k8s
    version: "1.32.0-rc1"
    k3s_version: "1"
    labels:
      github.owner: "k3s-io"
      github.repo: "k3s"
      autobump.sed_script: 's/\+k3s[0-9]//g'
      autobump.skip_if_contains: '["k3s"]' # disable autobump
    uri:
      - https://github.com/k3s-io/k3s
    license: "APL-2"
    description: " Lightweight Kubernetes "
  - name: k3s-openrc
    category: k8s
    version: "1.30.7"
    k3s_version: "1"
    labels:
      github.owner: "k3s-io"
      github.repo: "k3s"
      autobump.sed_script: 's/\+k3s1[0-9]//g'
      autobump.skip_if_contains: '["k3s"]' # disable autobump
    uri:
      - https://github.com/k3s-io/k3s
    license: "APL-2"
    description: " Lightweight Kubernetes "
  - name: k3s-openrc
    category: k8s
    version: "1.29.11"
    k3s_version: "1"
    labels:
      github.owner: "k3s-io"
      github.repo: "k3s"
      autobump.sed_script: 's/\+k3s[0-9]//g'
      autobump.skip_if_contains: '["k3s"]' # disable autobump
    uri:
      - https://github.com/k3s-io/k3s
    license: "APL-2"
    description: " Lightweight Kubernetes "
  - name: k3s-systemd
    category: k8s
    version: "1.32.0-rc1"
    k3s_version: "1"
    labels:
      github.owner: "k3s-io"
      github.repo: "k3s"
      autobump.sed_script: 's/\+k3s[0-9]//g'
      autobump.skip_if_contains: '["k3s"]' # disable autobump
    uri:
      - https://github.com/k3s-io/k3s
    license: "APL-2"
    description: " Lightweight Kubernetes "
  - name: k3s-systemd
    category: k8s
    version: "1.30.7"
    k3s_version: "1"
    labels:
      github.owner: "k3s-io"
      github.repo: "k3s"
      autobump.sed_script: 's/\+k3s[0-9]//g'
      autobump.skip_if_contains: '["k3s"]' # disable autobump
    uri:
      - https://github.com/k3s-io/k3s
    license: "APL-2"
    description: " Lightweight Kubernetes "
  - name: k3s-systemd
    category: k8s
    version: "1.29.11"
    k3s_version: "1"
    labels:
      github.owner: "k3s-io"
      github.repo: "k3s"
      autobump.sed_script: 's/\+k3s[0-9]//g'
      autobump.skip_if_contains: '["k3s"]' # disable autobump
    uri:
      - https://github.com/k3s-io/k3s
    license: "APL-2"
    description: " Lightweight Kubernetes "
