name: "helm"
category: "utils"
version: "4.0.2"
description: "The Kubernetes Package Manager"
license: "Apache-2.0"
labels:
  github.repo: "helm"
  github.owner: "helm"
  autobump.strategy: "release"
